spring:
  application:
    name: com.rawProject

  datasource:
    url: jdbc:postgresql://ep-odd-bar-aoe03nd2-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_yBt4NoA5LahZ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080